Finish documenting each command

diff --git a/tfw b/tfw
--- a/tfw
+++ b/tfw
@@ -3,104 +3,116 @@
 set -o errexit
 set -o pipefail
 
+if [[ "${DEBUG}" ]]; then
+  set -o xtrace
+fi
+
 __TFW_VERSION__='v0.1.0'
 declare -A __TFW_ALIASES__
 declare -A __TFW_HELP_DOC__
 
 main() {
-  if [[ "${DEBUG}" ]]; then
-    set -o xtrace
-  fi
-
   for key in "${!__TFW_ALIASES__[@]}"; do
     eval "__run_${key}() { __run_${__TFW_ALIASES__[${key}]} \"\${@}\"; }"
   done
 
   local command="${1}"
   shift || true
-  if "__run_${command}" "${@}"; then
+  if "__run_${command:-help}" "${@}"; then
     exit 0
   fi
   __run_help '' 1
 }
 
-aka() {
-  local dest="${1}"
+# <command[,alias,alias]> <docs>
+# Define the documentation and optional aliases for a given command.
+def() {
+  read -r -a dest_aliases <<<"${1//,/ }"
+  shift
+  local docs="${1}"
   shift || true
-  for key in "${@}"; do
+
+  local dest="${dest_aliases[0]}"
+
+  __TFW_HELP_DOC__[${dest}]="${docs}"
+  for key in "${dest_aliases[@]:1}"; do
     __TFW_ALIASES__[${key}]="${dest}"
+    __TFW_HELP_DOC__[${key}]="${docs}"
   done
 }
 
-doc() {
-  local topic="${1}"
-  shift || true
-  __TFW_HELP_DOC__[${topic}]="$*"
+__error() {
+  echo "ERROR: ${*}" >&2
 }
 
-__die() {
-  echo "${*}" >&2
-  exit 2
-}
+def help,h,-h,--help "[topic] [exit-code]
 
-aka help h -h --help
+Get more help about a topic, optionally injecting an exit code (mostly used
+internally)."
 __run_help() {
   local topic="${1}"
   local exit_code="${2:-0}"
 
-  if [[ "${__TFW_HELP_DOC__[${topic}]}" ]]; then
-    cat <<<"${__TFW_HELP_DOC__[${topic}]}"
-    exit "${exit_code}"
-  else
-    echo "ERROR: No help available for topic '${topic}'" >&2
+  if [[ "${topic}" ]]; then
+    if [[ ${__TFW_HELP_DOC__[${topic}]} ]]; then
+      echo -n "Usage: tfw ${topic} "
+      cat <<<"${__TFW_HELP_DOC__[${topic}]}"
+      exit "${exit_code}"
+    else
+      echo "ERROR: No help available for topic '${topic}'" >&2
+    fi
   fi
 
   cat <<'EOUSAGE'
-Usage: tfw <command> [${more-stuff(1)}, ${maybe(2)}]
+tfw <command> [${more-stuff(1)}, ${maybe(2)}]
 
-  h, help    - echo this string and exit or get help for another command
-  v, version - echo version and exit
+  help, h, -h, --help       - echo this string or get help for another command
+  version, v, -v, --version - echo version and exit
 
 Docker image configuration and deployment stuff:
 
-  e, extract   - extract ${name(1)} systemd files from ${image(2)}
-  p, printenv  - print env vars for ${name(1)} to ${out:-STDOUT(2)}
-  w, writeenv  - write env vars for ${name(1)} to ${RUNDIR}/ with a basename
-                 of ${name(1)}.env or ${custom_name(2)}.env if given
+  extract, e
+  printenv, p
+  writeenv, w
 
 Junk drawer utility stuff:
 
-  d, urldecode - print URL-decoded/unescaped ${strings(*)}
+  d, urldecode
 
 EOUSAGE
   exit "${exit_code}"
 }
 
-aka version v -v --version
+def version,v,-v,--version "
+
+Print the version and exit 0, and that's about it!"
 __run_version() {
   echo "${__TFW_VERSION__}"
   exit 0
 }
 
-aka urldecode d
-doc urldecode \
-"Usage: tfw urldecode <url-encoded-string> [url-encoded-string, ...]
+def urldecode,d "<url-encoded-string> [url-encoded-string, ...]
 
 URL-decode any number of positional argument strings, handling 'quote plus'
 encoding as well, e.g.
 
-  tfw urldecode what%2Fthe+what%3F
-"
+  tfw urldecode what%2Fthe+what%3F"
 __run_urldecode() {
   : "${*//+/ }"
   echo -e "${_//%/\\x}"
 }
 
-aka printenv p
+def printenv,p "<name> [outfile]
+
+Print the combined configuration for a given thing by name, optionally writing
+to a second \${outfile} argument.
+
+NOTE: \${ETCDIR} is used as prefix for \${ETCDIR}/default/"
 __run_printenv() {
   local name="${1}"
   if [[ ! "${name}" ]]; then
-    __die 'Missing positional argument for name'
+    __error 'Missing positional argument for name'
+    __run_help printenv 2
   fi
 
   local out="${2}"
@@ -128,7 +140,13 @@ __run_printenv() {
   done
 }
 
-aka writeenv w
+def writeenv,w "<name> [dest-basename]
+
+Write the combined configuration for a given thing by name to \${RUNDIR}/,
+defaulting to \${RUNDIR}/\${name}.env, but optionally to a custom dest basename.
+
+NOTE: \${ETCDIR} is used as prefix for \${ETCDIR}/default/\
+NOTE: \${RUNDIR} is used as prefix for \${RUNDIR}/\${name}.env"
 __run_writeenv() {
   local dest_basename="${2:-${1}}"
   local dest="${RUNDIR:-/var/tmp/travis-run.d}/${dest_basename}.env"
@@ -136,24 +154,32 @@ __run_writeenv() {
   __run_printenv "${1}" "${dest}"
 }
 
-aka extract e
+def extract,e "<name> <image>
+
+Extract systemd service definition and wrapper script, if present, from a given
+docker \${image} to system destinations, defaults being:
+
+service definition: \${ETCDIR:-/etc}/systemd/system/\${name}.service
+wrapper script:     \${USRSBINDIR:-/usr/sbin}/\${name}-wrapper
+
+NOTE: \${ETCDIR} is used as prefix for \${ETCDIR}/systemd/system\${name}.service
+NOTE: \${USRSBINDIR} is used as prefix for \${USRSBINDIR}/\${name}-wrapper"
 __run_extract() {
   local name="${1}"
   local image="${2}"
 
   if [[ ! "${name}" ]]; then
-    __die 'Missing positional argument for name'
+    __error 'Missing positional argument for name'
+    __run_help extract 2
   fi
 
   if [[ ! "${image}" ]]; then
-    __die 'Missing positional argument for image'
+    __error 'Missing positional argument for image'
+    __run_help extract 2
   fi
 
-  local extract_dir="${RUNDIR:-/var/tmp/travis-run.d}/${name}-extract.d"
   local service_dest="${ETCDIR:-/etc}/systemd/system/${name}.service"
   local wrapper_dest="${USRSBINDIR:-/usr/sbin}/${name}-wrapper"
-
-  mkdir -p "${extract_dir}"
 
   local tmpcontainer
   tmpcontainer="$(docker run -d --rm "${image}" sh -c "sleep 10")"
