Add gsub command to replace strings on extraction
and extend bootstrapping to also cover docker and check for dependency
executables

diff --git a/tfw b/tfw
--- a/tfw
+++ b/tfw
@@ -11,6 +11,19 @@ __TFW_VERSION__='v0.1.0'
 declare -A __TFW_ALIASES__
 declare -A __TFW_HELP_DOC__
 
+__TFW_DEPENDENCIES__=(
+  'awk'
+  'bash'
+  'cat'
+  'curl'
+  'cut'
+  'dirname'
+  'docker'
+  'jq'
+  'mktemp'
+  'tee'
+)
+
 main() {
   for key in "${!__TFW_ALIASES__[@]}"; do
     eval "__run_${key}() { __run_${__TFW_ALIASES__[${key}]} \"\${@}\"; }"
@@ -50,7 +63,15 @@ def() {
 }
 
 __error() {
-  echo "ERROR: ${*}" >&2
+  echo "tfw:ERROR: ${*}" >&2
+}
+
+__warn() {
+  echo "tfw:WARN: ${*}" >&2
+}
+
+__info() {
+  echo "tfw:INFO: ${*}" >&2
 }
 
 def help,h,-h,--help "[topic] [exit-code]
@@ -126,6 +147,13 @@ __run_bootstrap() {
 
   __bootstrap_jq
   __bootstrap_apt
+  __bootstrap_docker
+
+  for cmd in "${__TFW_DEPENDENCIES__[@]}"; do
+    if ! command -v "${cmd}" &>/dev/null; then
+      __warn "Could not find dependency '${cmd}'"
+    fi
+  done
 }
 
 __bootstrap_jq() {
@@ -169,6 +197,14 @@ __bootstrap_apt() {
     rsyslog-gnutls \
     software-properties-common \
     sudo
+}
+
+__bootstrap_docker() {
+  if docker version; then
+    return
+  fi
+
+  curl -sSL https://get.docker.io | bash
 }
 
 def printenv,p "<name> [outfile] [-E/--export]
@@ -258,7 +294,7 @@ __run_extract() {
     __run_help extract 2
   fi
 
-  local tmp_dest_prefix="$(mktemp)"
+  local tmp_dest_prefix="$(mktemp -d)"
   local service_dest="${ETCDIR:-/etc}/systemd/system/${name}.service"
   local service_dest_tmp="${tmp_dest_prefix}/${name}.service"
   local wrapper_dest="${USRSBINDIR:-/usr/sbin}/${name}-wrapper"
@@ -268,22 +304,28 @@ __run_extract() {
   tmpcontainer="$(docker run -d --rm "${image}" sh -c "sleep 10")"
 
   if docker cp "${tmpcontainer}:/app/systemd.service" "${service_dest_tmp}"; then
-    __run_gsub "${service_dest_tmp}" "${service_dest}"
-    echo "Extracted ${service_dest}"
+    local dest
+    dest="$(__run_gsub "${name}" "${service_dest_tmp}" "${service_dest}")"
+    echo "Extracted ${dest}"
   else
     echo "WARN: No systemd.service file found for ${name}" >&2
   fi
 
   if docker cp "${tmpcontainer}:/app/systemd-wrapper" "${wrapper_dest_tmp}"; then
-    __run_gsub "${wrapper_dest_tmp}" "${wrapper_dest}"
-    chmod +x "${wrapper_dest}"
-    echo "Extracted ${wrapper_dest}"
+    local dest
+    dest="$(__run_gsub "${name}" "${wrapper_dest_tmp}" "${wrapper_dest}")"
+    if [[ -w "${dest}" ]]; then
+      chmod +x "${dest}"
+      __info "Extracted ${dest}"
+    else
+      __error "Failed to extract ${wrapper_dest}"
+    fi
   else
-    echo "WARN: No systemd wrapper executable found for ${name}" >&2
+    __warn "No systemd wrapper executable found for ${name}"
   fi
 }
 
-def gsub,s "<infile> [outfile]
+def gsub,s "<name> <infile> [outfile]
 
 Substitute strings with platform and instance-dependent runtime values,
 optionally writing to an output file.
@@ -294,10 +336,23 @@ optionally writing to an output file.
   ___REGION_ZONE__    - region + zone, e.g. us-central1-d
 "
 __run_gsub() {
+  local name="${1}"
+  shift
   local infile="${1}"
   shift || true
+
+  if [[ ! "${name}" ]]; then
+    __error 'Missing positional argument for name'
+    __run_help gsub 2
+  fi
+
   if [[ ! "${infile}" ]]; then
     __error 'Missing positional argument for input file'
+    __run_help gsub 2
+  fi
+
+  if [[ ! -r "${infile}" ]]; then
+    __error 'Input file is not readable'
     __run_help gsub 2
   fi
 
@@ -312,34 +367,134 @@ __run_gsub() {
   instance_ipv4="$(__get_instance_ipv4)"
   instance_id="$(__get_instance_id)"
   instance_name="$(__get_instance_name)"
-  region_zone="$(__get_region_zone)"
+  region_zone="$(__get_instance_region_zone)"
+  local systemd_wrapper_path
+  systemd_wrapper_path="${USRSBINDIR}/${name}-wrapper"
 
-  while read -r line; do
+  while IFS= read -r line; do
+    line="${line//___SYSTEMD_WRAPPER___/${systemd_wrapper_path}}"
     line="${line//___INSTANCE_IPV4___/${instance_ipv4}}"
     line="${line//___INSTANCE_ID___/${instance_id}}"
     line="${line//___INSTANCE_NAME___/${instance_name}}"
-    echo "${line//___REGION_ZONE___/${region_zone}}"
+    line="${line//___REGION_ZONE___/${region_zone}}"
+    echo "${line}"
   done <"${infile}"
 }
 
 __get_instance_ipv4() {
-  local ipa='127.0.0.1'
-  echo "${ipa}"
+  __ensure_instance_metadata
+
+  local value='127.0.0.1'
+  if [[ -s "${RUNDIR}/instance-ipv4" ]]; then
+    value="$(cat "${RUNDIR}/instance-ipv4")"
+  fi
+  echo "${value}"
 }
 
 __get_instance_id() {
-  local iid='i-fafafaf'
-  echo "${iid}"
+  __ensure_instance_metadata
+
+  local value='i-fafafaf'
+  if [[ -s "${RUNDIR}/instance-id" ]]; then
+    value="$(cat "${RUNDIR}/instance-id")"
+  fi
+  echo "${value}"
 }
 
 __get_instance_name() {
-  local inm='notset'
-  echo "${inm}"
+  __ensure_instance_metadata
+
+  local value='notset'
+  if [[ -s "${RUNDIR}/instance-name" ]]; then
+    value="$(cat "${RUNDIR}/instance-name")"
+  fi
+  echo "${value}"
 }
 
-__get_region_zone() {
-  local rz='notset'
-  echo "${rz}"
+__get_instance_region_zone() {
+  __ensure_instance_metadata
+
+  local value='notset'
+  if [[ -s "${RUNDIR}/instance-region-zone" ]]; then
+    value="$(cat "${RUNDIR}/instance-region-zone")"
+  fi
+  echo "${value}"
+}
+
+__ensure_instance_metadata() {
+  if [[ -s "${RUNDIR}/instance-id" ]] &&
+     [[ -s "${RUNDIR}/instance-name" ]] &&
+     [[ -s "${RUNDIR}/instance-ipv4" ]] &&
+     [[ -s "${RUNDIR}/instance-region-zone" ]]; then
+    return
+  fi
+
+  if __fetch_instance_metadata_ec2; then
+    return
+  fi
+
+  if __fetch_instance_metadata_gce; then
+    return
+  fi
+
+  if __fetch_instance_metadata_packet; then
+    return
+  fi
+
+  __warn 'Failed to fetch any instance metadata'
+}
+
+__fetch_instance_metadata_ec2() {
+  local ec2_metadata='http://169.254.169.254/latest/meta-data'
+  if ! curl --connect-timeout 3 -sfSL \
+    "${ec2_metadata}/instance-id" &>/dev/null; then
+    return 1
+  fi
+
+  curl -sSL "${ec2_metadata}/instance-id" >"${RUNDIR}/instance-id"
+  local instance_id
+  instance_id="$(cat "${RUNDIR}/instance-id")"
+  echo "${instance_id:0:9}" >"${RUNDIR}/instance-name"
+  curl -sSL "${ec2_metadata}/local-ipv4" >"${RUNDIR}/instance-ipv4"
+  curl -sSL "${ec2_metadata}/placement/availability-zone" \
+    >"${RUNDIR}/instance-region-zone"
+  return 0
+}
+
+__fetch_instance_metadata_gce() {
+  local gce_metadata='http://metadata.google.internal/computeMetadata/v1'
+  if ! curl --connect-timeout 3 -sfSL -H 'Metadata-Flavor: Google' \
+      "${gce_metadata}/instance" &>/dev/null; then
+    return 1
+  fi
+
+  curl -sSL -H 'Metadata-Flavor: Google' \
+    "${gce_metadata}/instance/id" >"${RUNDIR}/instance-id"
+  curl -sSL -H 'Metadata-Flavor: Google' \
+    "${gce_metadata}/instance/name" >"${RUNDIR}/instance-name"
+  curl -sSL -H 'Metadata-Flavor: Google' \
+    "${gce_metadata}/instance/network-interfaces/0/ip" \
+    >"${RUNDIR}/instance-ipv4"
+  curl -sSL -H 'Metadata-Flavor: Google' \
+    "${gce_metadata}/instance/zone" |
+    awk -F/ '{ print $NF }' >"${RUNDIR}/instance-region-zone"
+  return 0
+}
+
+__fetch_instance_metadata_packet() {
+  local packet_metadata='https://metadata.packet.net/metadata'
+  if ! curl --connect-timeout 3 -sfSL "${packet_metadata}" &>/dev/null; then
+    return 1
+  fi
+
+  curl -sSL "${packet_metadata}" >"${RUNDIR}/metadata.json"
+  jq -r .id <"${RUNDIR}/metadata.json" | cut -d- -f 1 |
+    tee "${RUNDIR}/instance-name" >"${RUNDIR}/instance-id"
+  jq -r ".network.addresses | .[] | \
+    select(.address_family==4 and .public==false) | \
+    .address" <"${RUNDIR}/metadata.json" >"${RUNDIR}/instance-ipv4"
+  jq -r .facility <"${RUNDIR}/metadata.json" >"${RUNDIR}/instance-region-zone"
+  return 0
 }
 
 main "${@}"
